config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, presence: true, uniqueness: { scope: :list }
  validates :list, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :list, through: :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
 
  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(params[:list_id])
    else
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    @list = @bookmark.list
    redirect_to list_path(@list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<%= render 'shared/navbar' %>
<%= render 'shared/banner' %>
<div class="container">
  <div class="d-flex justify-content-between align-items-center my-3">
    <h2>My Lists</h2>
    <%= link_to "Create a new list", new_list_path, class:"btn btn-dark" %>
  </div>
  <div class="cards-wagon">
      <% @lists.each do |list| %>
        <% image_url = cl_image_path list.photo.key, height: 300, crop: :fill %>
        <div class="card-category-wagon" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_url %>)">
          <%= link_to "#{list.name}", list_path(list.id) %>
        </div>
      <% end %>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/lists/new.html.erb
<%= render 'shared/navbar' %>
<div class="container">
<h1>Create a new list</h1>
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class:"btn btn-primary"%>
<% end %>
</div>
<%= render 'shared/footer' %>

app/views/lists/show.html.erb
<%= render 'shared/navbar' %>
<%= render 'shared/list_banner', list: @list %>
<div class="container">
  <% movies = @list.movies %>
  <% bookmarks = @list.bookmarks %>
    <div class="row justify-content-around">
      <% bookmarks.each do |bookmark| %>
      <%= render "shared/movie_card", bookmark: bookmark %>
      <% end %>
    </div>
  <div class="row justify-content-center m-3 mt-5">
    <div class="col-12 col-lg-6">
    <h3 class="text-center">Create a new bookmark:</h3>
      <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment %>
          <%= f.association :movie %>
          <div class="dflex justify-content-center"><%= f.submit class:"btn btn-dark"%></div>
      <% end %>
    </div>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://photos.tf1info.fr/images/1280/720/cinemasafp2020-c209b3-0@1x.jpeg);">
  <div class="container">
    <h1> Save <strong>any movie</strong>!</h1>
    <p>Stop spending hours looking for a movie to watch.</p>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This app was made with <i class="fas fa-heart"></i> by Cannelle at Le Wagon
  </div>
</div>

app/views/shared/_list_banner.html.erb
 <% image_url = cl_image_path list.photo.key, height: 300, crop: :fill %>
<div class="banner" id="list-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_url %>)">
  <div class="container">
    <div class="justify-content-center mt-4 ">
        <h1> <%= @list.name %> </h1>
    </div>
  </div>
</div>

app/views/shared/_movie_card.html.erb
<div class="card mt-3" style="width: 18rem;">
<% image_url = bookmark.movie.poster_url %>
  <img src=<%= image_url %> class="card-img-top" alt="...">
  <div class="card-body d-flex flex-column">
    <h5 class="card-title fw-bold"><%= bookmark.movie.title %></h5>
    <p class="card-text"> <%= bookmark.movie.overview %> </p>
    <%= link_to "Delete", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-outline-dark mt-auto"%>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "popcorn_logo.jpg", alt: "Pop Corn Logo", id:"logo" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "All Lists", lists_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New List", new_list_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>